// AI-TOR brand mark: the "A" logo (two mirror-image trapezoid halves split by a thin vertical gap) + the header lockup (A over lowercase "ai-tor").
// GENERATED by tools/make_logo_icons.py from ai-tor-design/user-logo-a.svg (the single source of truth), cropped to its bounding box. Do not hand-edit.
const NS = 'http://www.w3.org/2000/svg';
export const MARK_VIEWBOX = '0 0 640 544';
export const MARK_PATH = 'M 314 0 L 0 544 L 314 544 L 314 448 L 166 448 L 314 192 Z M 326 0 L 640 544 L 326 544 L 326 448 L 474 448 L 326 192 Z';
/** Inline SVG mark, fill = currentColor. Size it with CSS (class 'brand-mark'); aspect 640:544. */
export function brandMark(cls = 'brand-mark') {
  const svg = document.createElementNS(NS, 'svg');
  svg.setAttribute('viewBox', MARK_VIEWBOX);
  svg.setAttribute('class', cls);
  svg.setAttribute('aria-hidden', 'true');
  svg.setAttribute('focusable', 'false');
  const p = document.createElementNS(NS, 'path');
  p.setAttribute('d', MARK_PATH);
  p.setAttribute('fill', 'currentColor');
  svg.append(p);
  return svg;
}
/** Header lockup: the A mark centred on top, lowercase "ai-tor" directly beneath it (League Spartan Bold, ~0.26em tracking). Size via --lk (mark width). */
export function lockup(cls = 'lockup') {
  const d = document.createElement('div');
  d.className = cls;
  const w = document.createElement('span');
  w.className = 'wordmark';
  w.textContent = 'ai-tor';
  d.append(brandMark(), w);
  return d;
}
