// AI-TOR brand mark: the user's logo (two mirror-image triangles split by a vertical gap).
// GENERATED by tools/make_logo_icons.py from ai-tor-design/user-logo.svg (the single source of truth), cropped to its bounding box. Do not hand-edit.
const NS = 'http://www.w3.org/2000/svg';
export const MARK_VIEWBOX = '0 0 560 516';
export const MARK_PATH = 'M 242 0 L 242 442 L 0 516 Z M 318 0 L 318 442 L 560 516 Z';
/** Inline SVG mark, fill = currentColor. Size it with CSS (class 'brand-mark'); aspect 560:516. */
export function brandMark(cls = 'brand-mark') {
  const svg = document.createElementNS(NS, 'svg');
  svg.setAttribute('viewBox', MARK_VIEWBOX);
  svg.setAttribute('class', cls);
  svg.setAttribute('aria-hidden', 'true');
  svg.setAttribute('focusable', 'false');
  const p = document.createElementNS(NS, 'path');
  p.setAttribute('d', MARK_PATH);
  p.setAttribute('fill', 'currentColor');
  svg.append(p);
  return svg;
}
