// Bundled offline list of countries (193 UN member states + Vatican City + Palestine = 195).
// [ISO 3166-1 alpha-2 code, name, continent, search aliases]. No network; static data. v19: no flag emoji; the UI shows the 2-letter ISO code in a flat chip (isoLabel).
export const CONTINENTS = ["Africa", "Asia", "Europe", "North America", "South America", "Oceania"];
export const COUNTRIES = [
  ["DZ", "Algeria", "Africa", ""],
  ["AO", "Angola", "Africa", ""],
  ["BJ", "Benin", "Africa", ""],
  ["BW", "Botswana", "Africa", ""],
  ["BF", "Burkina Faso", "Africa", ""],
  ["BI", "Burundi", "Africa", ""],
  ["CV", "Cabo Verde", "Africa", "Cape Verde"],
  ["CM", "Cameroon", "Africa", ""],
  ["CF", "Central African Republic", "Africa", ""],
  ["TD", "Chad", "Africa", ""],
  ["KM", "Comoros", "Africa", ""],
  ["CG", "Republic of the Congo", "Africa", "Congo Brazzaville"],
  ["CD", "DR Congo", "Africa", "Democratic Republic of the Congo,Congo Kinshasa"],
  ["CI", "Côte d'Ivoire", "Africa", "Ivory Coast"],
  ["DJ", "Djibouti", "Africa", ""],
  ["EG", "Egypt", "Africa", ""],
  ["GQ", "Equatorial Guinea", "Africa", ""],
  ["ER", "Eritrea", "Africa", ""],
  ["SZ", "Eswatini", "Africa", "Swaziland"],
  ["ET", "Ethiopia", "Africa", ""],
  ["GA", "Gabon", "Africa", ""],
  ["GM", "Gambia", "Africa", ""],
  ["GH", "Ghana", "Africa", ""],
  ["GN", "Guinea", "Africa", ""],
  ["GW", "Guinea-Bissau", "Africa", ""],
  ["KE", "Kenya", "Africa", ""],
  ["LS", "Lesotho", "Africa", ""],
  ["LR", "Liberia", "Africa", ""],
  ["LY", "Libya", "Africa", ""],
  ["MG", "Madagascar", "Africa", ""],
  ["MW", "Malawi", "Africa", ""],
  ["ML", "Mali", "Africa", ""],
  ["MR", "Mauritania", "Africa", ""],
  ["MU", "Mauritius", "Africa", ""],
  ["MA", "Morocco", "Africa", ""],
  ["MZ", "Mozambique", "Africa", ""],
  ["NA", "Namibia", "Africa", ""],
  ["NE", "Niger", "Africa", ""],
  ["NG", "Nigeria", "Africa", ""],
  ["RW", "Rwanda", "Africa", ""],
  ["ST", "São Tomé and Príncipe", "Africa", ""],
  ["SN", "Senegal", "Africa", ""],
  ["SC", "Seychelles", "Africa", ""],
  ["SL", "Sierra Leone", "Africa", ""],
  ["SO", "Somalia", "Africa", ""],
  ["ZA", "South Africa", "Africa", ""],
  ["SS", "South Sudan", "Africa", ""],
  ["SD", "Sudan", "Africa", ""],
  ["TZ", "Tanzania", "Africa", ""],
  ["TG", "Togo", "Africa", ""],
  ["TN", "Tunisia", "Africa", ""],
  ["UG", "Uganda", "Africa", ""],
  ["ZM", "Zambia", "Africa", ""],
  ["ZW", "Zimbabwe", "Africa", ""],
  ["AF", "Afghanistan", "Asia", ""],
  ["AM", "Armenia", "Asia", ""],
  ["AZ", "Azerbaijan", "Asia", ""],
  ["BH", "Bahrain", "Asia", ""],
  ["BD", "Bangladesh", "Asia", ""],
  ["BT", "Bhutan", "Asia", ""],
  ["BN", "Brunei", "Asia", ""],
  ["KH", "Cambodia", "Asia", ""],
  ["CN", "China", "Asia", ""],
  ["CY", "Cyprus", "Asia", ""],
  ["GE", "Georgia", "Asia", ""],
  ["IN", "India", "Asia", ""],
  ["ID", "Indonesia", "Asia", ""],
  ["IR", "Iran", "Asia", ""],
  ["IQ", "Iraq", "Asia", ""],
  ["IL", "Israel", "Asia", ""],
  ["JP", "Japan", "Asia", ""],
  ["JO", "Jordan", "Asia", ""],
  ["KZ", "Kazakhstan", "Asia", ""],
  ["KW", "Kuwait", "Asia", ""],
  ["KG", "Kyrgyzstan", "Asia", ""],
  ["LA", "Laos", "Asia", ""],
  ["LB", "Lebanon", "Asia", ""],
  ["MY", "Malaysia", "Asia", ""],
  ["MV", "Maldives", "Asia", ""],
  ["MN", "Mongolia", "Asia", ""],
  ["MM", "Myanmar", "Asia", "Burma"],
  ["NP", "Nepal", "Asia", ""],
  ["KP", "North Korea", "Asia", ""],
  ["OM", "Oman", "Asia", ""],
  ["PK", "Pakistan", "Asia", ""],
  ["PS", "Palestine", "Asia", ""],
  ["PH", "Philippines", "Asia", ""],
  ["QA", "Qatar", "Asia", ""],
  ["SA", "Saudi Arabia", "Asia", ""],
  ["SG", "Singapore", "Asia", ""],
  ["KR", "South Korea", "Asia", "Korea"],
  ["LK", "Sri Lanka", "Asia", ""],
  ["SY", "Syria", "Asia", ""],
  ["TJ", "Tajikistan", "Asia", ""],
  ["TH", "Thailand", "Asia", ""],
  ["TL", "Timor-Leste", "Asia", "East Timor"],
  ["TR", "Türkiye", "Asia", "Turkey"],
  ["TM", "Turkmenistan", "Asia", ""],
  ["AE", "United Arab Emirates", "Asia", "UAE,Dubai"],
  ["UZ", "Uzbekistan", "Asia", ""],
  ["VN", "Vietnam", "Asia", ""],
  ["YE", "Yemen", "Asia", ""],
  ["AL", "Albania", "Europe", ""],
  ["AD", "Andorra", "Europe", ""],
  ["AT", "Austria", "Europe", ""],
  ["BY", "Belarus", "Europe", ""],
  ["BE", "Belgium", "Europe", ""],
  ["BA", "Bosnia and Herzegovina", "Europe", ""],
  ["BG", "Bulgaria", "Europe", ""],
  ["HR", "Croatia", "Europe", ""],
  ["CZ", "Czechia", "Europe", "Czech Republic"],
  ["DK", "Denmark", "Europe", ""],
  ["EE", "Estonia", "Europe", ""],
  ["FI", "Finland", "Europe", ""],
  ["FR", "France", "Europe", ""],
  ["DE", "Germany", "Europe", ""],
  ["GR", "Greece", "Europe", ""],
  ["HU", "Hungary", "Europe", ""],
  ["IS", "Iceland", "Europe", ""],
  ["IE", "Ireland", "Europe", ""],
  ["IT", "Italy", "Europe", ""],
  ["LV", "Latvia", "Europe", ""],
  ["LI", "Liechtenstein", "Europe", ""],
  ["LT", "Lithuania", "Europe", ""],
  ["LU", "Luxembourg", "Europe", ""],
  ["MT", "Malta", "Europe", ""],
  ["MD", "Moldova", "Europe", ""],
  ["MC", "Monaco", "Europe", ""],
  ["ME", "Montenegro", "Europe", ""],
  ["NL", "Netherlands", "Europe", "Holland"],
  ["MK", "North Macedonia", "Europe", "Macedonia"],
  ["NO", "Norway", "Europe", ""],
  ["PL", "Poland", "Europe", ""],
  ["PT", "Portugal", "Europe", ""],
  ["RO", "Romania", "Europe", ""],
  ["RU", "Russia", "Europe", ""],
  ["SM", "San Marino", "Europe", ""],
  ["RS", "Serbia", "Europe", ""],
  ["SK", "Slovakia", "Europe", ""],
  ["SI", "Slovenia", "Europe", ""],
  ["ES", "Spain", "Europe", ""],
  ["SE", "Sweden", "Europe", ""],
  ["CH", "Switzerland", "Europe", ""],
  ["UA", "Ukraine", "Europe", ""],
  ["GB", "United Kingdom", "Europe", "UK,England,Scotland,Wales,Great Britain"],
  ["VA", "Vatican City", "Europe", "Holy See"],
  ["AG", "Antigua and Barbuda", "North America", ""],
  ["BS", "Bahamas", "North America", ""],
  ["BB", "Barbados", "North America", ""],
  ["BZ", "Belize", "North America", ""],
  ["CA", "Canada", "North America", ""],
  ["CR", "Costa Rica", "North America", ""],
  ["CU", "Cuba", "North America", ""],
  ["DM", "Dominica", "North America", ""],
  ["DO", "Dominican Republic", "North America", ""],
  ["SV", "El Salvador", "North America", ""],
  ["GD", "Grenada", "North America", ""],
  ["GT", "Guatemala", "North America", ""],
  ["HT", "Haiti", "North America", ""],
  ["HN", "Honduras", "North America", ""],
  ["JM", "Jamaica", "North America", ""],
  ["MX", "Mexico", "North America", ""],
  ["NI", "Nicaragua", "North America", ""],
  ["PA", "Panama", "North America", ""],
  ["KN", "Saint Kitts and Nevis", "North America", ""],
  ["LC", "Saint Lucia", "North America", ""],
  ["VC", "Saint Vincent and the Grenadines", "North America", ""],
  ["TT", "Trinidad and Tobago", "North America", ""],
  ["US", "United States", "North America", "USA,America,US"],
  ["AR", "Argentina", "South America", ""],
  ["BO", "Bolivia", "South America", ""],
  ["BR", "Brazil", "South America", ""],
  ["CL", "Chile", "South America", ""],
  ["CO", "Colombia", "South America", ""],
  ["EC", "Ecuador", "South America", ""],
  ["GY", "Guyana", "South America", ""],
  ["PY", "Paraguay", "South America", ""],
  ["PE", "Peru", "South America", ""],
  ["SR", "Suriname", "South America", ""],
  ["UY", "Uruguay", "South America", ""],
  ["VE", "Venezuela", "South America", ""],
  ["AU", "Australia", "Oceania", ""],
  ["FJ", "Fiji", "Oceania", ""],
  ["KI", "Kiribati", "Oceania", ""],
  ["MH", "Marshall Islands", "Oceania", ""],
  ["FM", "Micronesia", "Oceania", ""],
  ["NR", "Nauru", "Oceania", ""],
  ["NZ", "New Zealand", "Oceania", ""],
  ["PW", "Palau", "Oceania", ""],
  ["PG", "Papua New Guinea", "Oceania", ""],
  ["WS", "Samoa", "Oceania", ""],
  ["SB", "Solomon Islands", "Oceania", ""],
  ["TO", "Tonga", "Oceania", ""],
  ["TV", "Tuvalu", "Oceania", ""],
  ["VU", "Vanuatu", "Oceania", ""],
].map(([code, name, continent, aliases]) => Object.freeze({ code, name, continent, aliases }));
/** 2-letter label for the flat ISO chip: the ISO 3166-1 alpha-2 code; falls back to the initials of the name if a code is ever missing/invalid. */
export const isoLabel = (c) => {
  const code = String((c && c.code) || '').toUpperCase();
  if (/^[A-Z]{2}$/.test(code)) return code;
  const w = String((c && c.name) || '?').replace(/[^A-Za-z ]/g, ' ').trim().split(/\s+/).filter(Boolean);
  return ((w.length > 1 ? w[0][0] + w[1][0] : (w[0] || '?').slice(0, 2)) || '?').toUpperCase();
};
