#!/usr/bin/env python3
"""AI-TOR icon set from the user's mark (/workspace/ai-tor-design/user-logo-a.svg = single source of truth).
Writes icons/{icon-192,icon-512,maskable-192,maskable-512,apple-touch-icon,favicon-32}.png + favicon.svg into the app and
/workspace/ai-tor-design/logo-icons/ (plus icon.svg, maskable.svg, favicon-16/48, favicon.ico).
Run: python3 /workspace/tools/make_logo_icons.py    (needs playwright + /usr/bin/google-chrome, Pillow)
The mark itself is never altered: white fill, pure geometry from user-logo.json. Only the surround (background, crimson glow, Mars horizon rim) is decoration."""
import json, re, shutil
from pathlib import Path
from playwright.sync_api import sync_playwright
from PIL import Image
D = Path('/workspace/ai-tor-design'); APP = Path('/workspace/ai-tor'); OUT = D/'logo-icons'
def load_mark():
    """Read the single source of truth user-logo-a.svg (M/L/Z polygons), crop to the tight bbox, return (w, h, d)."""
    t = (D/'user-logo-a.svg').read_text()
    ds = re.findall(r'\sd="([^"]+)"', t)
    toks = re.findall(r'[MLZ]|-?\d+(?:\.\d+)?', ' '.join(ds))
    pts, out, i = [], [], 0
    while i < len(toks):
        if toks[i] in 'MLZ':
            if toks[i] != 'Z': pts.append((float(toks[i+1]), float(toks[i+2])))
            i += 3 if toks[i] != 'Z' else 1
        else: i += 1
    x0 = min(x for x, _ in pts); y0 = min(y for _, y in pts); x1 = max(x for x, _ in pts); y1 = max(y for _, y in pts)
    k = 0; res = []
    for t_ in toks:
        if t_ in 'MLZ': res.append(t_); k = 0
        else:
            v = float(t_) - (x0 if k % 2 == 0 else y0); k += 1; res.append(f'{v:g}')
    d = re.sub(r' ?Z ?', ' Z ', ' '.join(res)).strip()
    return x1-x0, y1-y0, d
VW, VH, DPATH = load_mark()
# palette = css/app.css tokens
BG, SKY_MID, MARS, EMBER, RUST, BLOOD, RIM = '#0a0305', '#2a0810', '#d93a2d', '#ff5238', '#5a0f0f', '#8f1a1c', '#ff4a2e'

BRAND_JS = f"""// AI-TOR brand mark: the "A" logo (two mirror-image trapezoid halves split by a thin vertical gap) + the header lockup (A over lowercase "ai-tor").
// GENERATED by tools/make_logo_icons.py from ai-tor-design/user-logo-a.svg (the single source of truth), cropped to its bounding box. Do not hand-edit.
const NS = 'http://www.w3.org/2000/svg';
export const MARK_VIEWBOX = '0 0 {VW:g} {VH:g}';
export const MARK_PATH = '{DPATH}';
/** Inline SVG mark, fill = currentColor. Size it with CSS (class 'brand-mark'); aspect {VW:g}:{VH:g}. */
export function brandMark(cls = 'brand-mark') {{
  const svg = document.createElementNS(NS, 'svg');
  svg.setAttribute('viewBox', MARK_VIEWBOX);
  svg.setAttribute('class', cls);
  svg.setAttribute('aria-hidden', 'true');
  svg.setAttribute('focusable', 'false');
  const p = document.createElementNS(NS, 'path');
  p.setAttribute('d', MARK_PATH);
  p.setAttribute('fill', 'currentColor');
  svg.append(p);
  return svg;
}}
/** Header lockup: the A mark centred on top, lowercase "ai-tor" directly beneath it (League Spartan Bold, ~0.26em tracking). Size via --lk (mark width). */
export function lockup(cls = 'lockup') {{
  const d = document.createElement('div');
  d.className = cls;
  const w = document.createElement('span');
  w.className = 'wordmark';
  w.textContent = 'ai-tor';
  d.append(brandMark(), w);
  return d;
}}
"""

def svg(kind):
    """kind: any (square, opaque; mark at board scale) | full (maskable + apple-touch: mark inside the 80% safe circle) | fav (small, bold mark).
    Flat: solid BG, white mark, nothing else."""
    S = 1024
    w = {'any': VW/S, 'full': .54, 'fav': .80}[kind]          # mark width as a share of the canvas (board v5: 640/1024)
    sc = w*S/VW; mh = VH*sc
    tx, ty = S/2 - w*S/2, S/2 - mh/2
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="{S}" height="{S}" viewBox="0 0 {S} {S}">
  <rect width="{S}" height="{S}" fill="{BG}"/>
  <path transform="translate({tx:.2f} {ty:.2f}) scale({sc:.5f})" d="{DPATH}" fill="#ffffff"/>
</svg>'''

def render(browser, s, out, px, transparent):
    p = browser.new_page(viewport={'width': px, 'height': px})
    s = s.replace('width="1024" height="1024"', f'width="{px}" height="{px}"', 1)
    p.set_content(f'<html><body style="margin:0;background:transparent">{s}</body></html>')
    p.screenshot(path=str(out), omit_background=transparent, clip={'x': 0, 'y': 0, 'width': px, 'height': px}); p.close()

def favicon_svg():   # tiny, hand-written, flat: the mark on the dark tile
    w = .80*64; sc = w/VW; h = VH*sc
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" fill="{BG}"/>'
            f'<path transform="translate({32-w/2:.2f} {32-h/2:.2f}) scale({sc:.5f})" d="{DPATH}" fill="#fff"/></svg>\n')

def main():
    OUT.mkdir(exist_ok=True); (APP/'icons').mkdir(exist_ok=True)
    any_s, full_s, fav_s = svg('any'), svg('full'), svg('fav')
    (OUT/'icon.svg').write_text(any_s); (OUT/'maskable.svg').write_text(full_s); (OUT/'favicon.svg').write_text(favicon_svg())
    with sync_playwright() as pw:
        b = pw.chromium.launch(executable_path='/usr/bin/google-chrome', args=['--no-sandbox'])
        render(b, any_s, OUT/'icon-1024.png', 1024, True)
        for px in (192, 512):
            render(b, any_s, OUT/f'icon-{px}.png', px, True)
            render(b, full_s, OUT/f'maskable-{px}.png', px, False)
        render(b, any_s, OUT/'apple-touch-icon.png', 180, False)       # opaque, square: iOS applies its own rounding
        for px in (16, 32, 48): render(b, fav_s, OUT/f'favicon-{px}.png', px, True)
        b.close()
    Image.open(OUT/'favicon-48.png').save(OUT/'favicon.ico', sizes=[(16, 16), (32, 32), (48, 48)])
    for n in ('icon-192.png', 'icon-512.png', 'maskable-192.png', 'maskable-512.png', 'apple-touch-icon.png', 'favicon-32.png', 'favicon.svg', 'favicon.ico'):
        shutil.copyfile(OUT/n, APP/'icons'/n)
    (APP/'js'/'brand.js').write_text(BRAND_JS)
    print('icons written to', OUT, 'and', APP/'icons')
main()
