#!/usr/bin/env python3
"""Generates css/chamfer.css (v24): every rectangle inside a section page gets exactly TWO chamfers on OPPOSITE corners (top-left + bottom-right).
Edit the GROUPS below (selector lists per size / default line colour) and re-run:  python3 tools/make_chamfer_css.py

How it works (all in the generated file):
 * clip-path: polygon(...) cuts the TL and BR corners by --c (8px large, 5px small, 4px badges / checkboxes). The other two corners stay sharp.
 * clip-path would also clip a real CSS border (the diagonals would have no line), so the outline is drawn by 6 background gradients instead:
   four 1px edge strips + two 45-degree bands that follow the cut. The strips never overlap the bands (no doubled-alpha dots at the joints) and the real
   border is made transparent (it only keeps the layout). One colour source: --cf-line (and --cf-t for the thickness), so every state is one custom property.
 * focus-visible: an outline would be clipped, so a focused element gets a 2px Ember outline drawn the same way (--cf-line: focus, --cf-t: 2px).
"""
import pathlib

# (selectors, chamfer var, default line colour or None for a fill-only element)
GROUPS = [
  ('.card, details.group, details.src-all, .dst-bar-card, .dst-sec, .feedbar, #networth', '--cf', 'var(--surf-line-lo)'),
  ('.fin-head, .trv-searchrow, .app-foot, .dialog, .toast, .btn, .ghost, input[type=text], input[type=date], input[type=password], input[type=search], select, textarea, .todo-add-input, .feed-formrow input, .trv-search', '--cf', 'var(--surf-line)'),
  ('.banner, .form-err', '--cf', 'var(--ember)'),
  ('.trv-tab', '--cf', 'transparent'),
  ('.dst-row', '--cf-s', 'var(--surf-line-lo)'),
  ('.todo-comment', '--cf-s', 'var(--hair)'),
  ('.todo-paste-item', '--cf-s', 'var(--surf-line)'),
  ('.chip, .todo-chip, .dst-kind', '--cf-s', 'var(--hair-2)'),
  ('.trv-pill', '--cf-s', 'var(--green-line)'),
  ('.dst-chip, .iso, .back', '--cf-s', 'transparent'),
  ('.trv-tabbadge, .dst-new, .todo-tabn', '--cf-xs', 'transparent'),
  ('.trv-cb, .todo-cb, .set-cb', '--cf-xs', 'var(--surf-line)'),
]
UNION = ', '.join(g[0] for g in GROUPS)
L = 'var(--cf-line)'
HEAD = f"""/* AI-TOR v24 CHAMFERS (generated by tools/make_chamfer_css.py: edit the groups there). Loaded last, after flat.css.
   Every rectangle INSIDE a section page (cards, tabs, buttons, inputs, rows, chips, dialogs, toasts, checkboxes) has exactly 2 chamfers on OPPOSITE corners:
   top-left + bottom-right. The other two corners stay sharp. The home wheel and the splash are not touched.
   Sizes: --cf 8px (cards, buttons, inputs, tabs, dialogs), --cf-s 5px (list rows, chips, small tabs), --cf-xs 4px (badges, checkboxes). Change them here once:   */
:root{{--cf:8px;--cf-s:5px;--cf-xs:4px}}

/* 1) size + default outline colour per group (specificity 0, so any state rule below wins) */
"""
out = [HEAD]
for sel, size, col in GROUPS:
    out.append(f":where({sel}){{--c:var({size});--cf-line:{col}}}\n")
shape = f"""
/* 2) the shape and the outline (one rule for all of them).
      The real border only keeps the 1px of layout (transparent); the visible outline is the 6 gradients: top / right / bottom / left strips (each stops short of the chamfers) + the two 45-degree bands. */
:where({UNION}){{
  --cf-t:1px;--cf-tt:var(--cf-t);--cf-k:calc(var(--c) + .9px);--cf-d:calc(var(--c) + 5px);--cf-p:calc(var(--c)*.7071 + var(--cf-t)*.8);
  clip-path:polygon(var(--c) 0,100% 0,100% calc(100% - var(--c)),calc(100% - var(--c)) 100%,0 100%,0 var(--c));
  border-color:transparent!important;
  background-origin:border-box!important;background-repeat:no-repeat!important;
  background-image:
    linear-gradient(var(--cf-tline,{L}),var(--cf-tline,{L})),
    linear-gradient({L},{L}),
    linear-gradient({L},{L}),
    linear-gradient({L},{L}),
    linear-gradient(135deg,{L} 0,{L} var(--cf-p),transparent calc(var(--cf-p) + .8px)),
    linear-gradient(315deg,{L} 0,{L} var(--cf-p),transparent calc(var(--cf-p) + .8px))!important;
  background-size:
    calc(100% - var(--cf-k) - var(--cf-t)) var(--cf-tt),
    var(--cf-t) calc(100% - var(--cf-k)),
    calc(100% - var(--cf-k) - var(--cf-t)) var(--cf-t),
    var(--cf-t) calc(100% - var(--cf-k)),
    var(--cf-d) var(--cf-d),
    var(--cf-d) var(--cf-d)!important;
  background-position:
    var(--cf-k) 0,
    100% 0,
    var(--cf-t) 100%,
    0 100%,
    0 0,
    100% 100%!important;
}}
"""
out.append(shape)
out.append("""
/* 3) states = only the outline colour / weight (custom properties), never border-color */
#networth{--cf-tline:var(--mars);--cf-tt:2px}
.card.error{--cf-line:var(--red-line)}
.card.na{--cf-line:var(--hair-2)}
.chip.warn,.todo-chip.today,.dst-down{--cf-line:var(--amber-line)}
.chip.ok{--cf-line:var(--green-line)}
.todo-chip.overdue{--cf-line:var(--red-line)}
.todo-chip.cmt,.todo-chip.src,.dst-kind-country,.dst-kind-state,.dst-kind-city,.dst-kind-activity,.dst-kind-museum{--cf-line:var(--surf-line)}
.btn:active,.dst-row:active,.dst-row.is-new,.trv-cb:active,.todo-cb:active,.set-cb:active,.trv-cb:checked,.todo-cb:checked,.set-cb:checked{--cf-line:var(--ember)}
.btn.primary{--cf-line:var(--mars)}
.btn.primary:active,.btn.danger{--cf-line:var(--ember)}
.dst-row.is-new:active{--cf-line:var(--ember)}
input[type=text]:focus-visible,input[type=date]:focus-visible,input[type=password]:focus-visible,input[type=search]:focus-visible,select:focus-visible,textarea:focus-visible,
.todo-add-input:focus-visible,.feed-formrow input:focus-visible,.trv-search:focus-visible{--cf-line:var(--ember);--cf-t:2px;outline:none}

/* 4) keyboard focus: an outline would be cut by the clip-path, so it is drawn inside as a 2px line that follows the chamfers */
""")
foc = [s.strip() for g in GROUPS for s in g[0].split(',')]
foc = [s for s in foc if not s.startswith('#') and not s.startswith('input[') and s not in ('select', 'textarea', '.todo-add-input', '.feed-formrow input', '.trv-search', 'details.group', 'details.src-all')]
out.append(',\n'.join(f"{s}:focus-visible" for s in foc) + "{--cf-line:var(--focus);--cf-t:2px;outline:none}\n")
out.append("""@supports selector(:has(a)){
  details.group:has(>summary:focus-visible),details.src-all:has(>summary:focus-visible){--cf-line:var(--focus);--cf-t:2px}
  details.group>summary:focus-visible,details.src-all>summary:focus-visible{outline:none}
}

/* 5) high-contrast / forced-colors: plain rectangles with a real border (the gradient outline is not drawn there) */
@media (forced-colors:active){:where(""" + UNION + """){clip-path:none;border-color:CanvasText!important;background-image:none!important}}
""")
pathlib.Path(__file__).resolve().parent.parent.joinpath('css/chamfer.css').write_text(''.join(out))
print('wrote css/chamfer.css', sum(len(x) for x in out), 'bytes')
